# Generated by Django 3.2.9 on 2022-01-10 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('city_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft', models.CharField(max_length=255)),
                ('flight_code', models.CharField(max_length=255)),
                ('departure_date', models.DateTimeField()),
                ('price_economy', models.CharField(max_length=255)),
                ('price_business', models.CharField(max_length=255)),
                ('price_first_class', models.CharField(max_length=255)),
                ('max_capacity_economy', models.IntegerField()),
                ('max_capacity_business', models.IntegerField()),
                ('max_capacity_first_class', models.IntegerField()),
                ('from_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='from_location', to='booking.location')),
                ('to_destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='to_destination', to='booking.location')),
            ],
        ),
    ]
